### ISSUE TITLE
Implementing varying instrumental resolution for Non-SDSS spectra

### ISSUE THREAD

**Issue by rremigio** [remingtonsexton/BADASS3#1]
I am trying to use BADASS on some MUSE datacubes that span a large wavelength range (from Hb/[OIII] all the way to Ca II triplet), and would like to take into account the fact that the instrumental resolution is itself a function of wavelength (e.g. LSF equations 7 and 8 in Bacon et al. 2017: [https://www.aanda.org/articles/aa/pdf/2017/12/aa30833-17.pdf](url).  

prepare_user_spec seems to expect that fwhm is either an int or a float, and would like to know if this could be taken into account by simply using something like fwhm_gal = fwhm[mask], similar to the prepare_ifu_spec routine, or if something else needs to be done entirely.

**Comment by remingtonsexton** [comment]
Hello,

Yes we knew there was a wavelength dependence but didn't put much thought into it.  Just now, Michael Reefe, who developed the IFU support for BADASS, has implemented equation 7 from Bacon et al. as the default for MUSE cubes in BADASS.  We have also added a MUSE example notebook and an accompanying MUSE subcube for it to work with.  We also patched a few bugs.  Hopefully this helps.

Thanks,
Remington
________________________________
From: rremigio ***@***.***>
Sent: Tuesday, May 10, 2022 4:51 PM
To: remingtonsexton/BADASS3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [remingtonsexton/BADASS3] Implementing varying instrumental resolution for Non-SDSS spectra (Issue #1)


I am trying to use BADASS on some MUSE datacubes that span a large wavelength range (from Hb/[OIII] all the way to Ca II triplet), and would like to take into account the fact that the instrumental resolution is itself a function of wavelength (e.g. LSF equations 7 and 8 in Bacon et al. 2017: https://www.aanda.org/articles/aa/pdf/2017/12/aa30833-17.pdf<url>.

prepare_user_spec seems to expect that fwhm is either an int or a float, and would like to know if this could be taken into account by simply using something like fwhm_gal = fwhm[mask], similar to the prepare_ifu_spec routine, or if something else needs to be done entirely.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/11DUFyUPvRnwKGYenV91XNObcK1xTFZIQeMTRIQvb8EGWQLkTBtBUIIYQownRyOuyFmsz8UknNhrYgCM_7Rjw_Z1B_fUsvo_vniggpk9pCHXVqJygz1H59AOpB5erdWce1QnU-0CC_HGSeU8O6cMkhr9UAcLBZ02guBnWkMtWGeZfpJ8x9QmFhcSO0arbhyBtSmXqJZ9boMuRzAHQ0IpRkYf50Wdw6LEkRuHgxY92vZHcPQinymCUD5s_iyjeE9hUUG8rthfRMugHBdhfgzxV73N4Zj9S92c6scTzl1Wl6B7KixYYSNZH536NwtZ1OyRuGYhhUimGTkrnTUv1kioYEuchH_cBVydbw-LFoCi7CAUXL9trlWUL8kXYbpoJGfwt44NDrKJTRXydYWQy4HOusmDwjZYuSWM_jz1EZS6vbkB3BPhZXqfnRRGSFo7hbcbr/https%3A%2F%2Fgithub.com%2Fremingtonsexton%2FBADASS3%2Fissues%2F1>, or unsubscribe<https://secure-web.cisco.com/1NYA5cJs9whj4ImqOrTsGxE--KPArJdn-P2EoF-1F5KAxtABsxKHYDaa8pUUTI--5sUrGtFsssbCCa6o0d_gCTVmyfOm9Y7-vln0kSvlBSFXOW_N6mqbr5s8jR0DbN8cOK4HQmUhdIzT3PsDMfYB-SZRKTI6LYUt3immLM6WbdW81vzFLRVr3xxbUfbxafKmEIAsNP5ahc8M8-FpbhOLDIC-9JduNC-JA4vhkJR2ixWvwY_tqKA9fd8YEnSwyE-RWn!
%209J484q0Qv0XZlrRT9i1IfdesBqqsWr7VyXH7DOi7Ek_4KfQW2joJfWD-XZNAqm6YVrc6yRR6Fwdu5g1013G8aqQnf_zeL3m2tsdVCwNHDIUm_4awAiuK8PNOA6YfJ_2_M0xF6IDuQL2N3uiTy8VVWrfa-OXVOR1JQEt3Mk-0dnYaFDs2daG6bBp8KdZqBC6/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF7IPQHZMDIF2APW6KRH7WDVJLD5RANCNFSM5VSZYSJA>.

**Comment by rremigio** [comment]
Thank you to you and Michael for being so quick to update BADASS. This update helps nicely.
