### ISSUE TITLE
Issue while creating the reconstructed data cube

### ISSUE THREAD

**Issue by arshiali1701** [remingtonsexton/BADASS3#12]
Hello.
I'm trying to do analysis on a MUSE ifu and constantly being encountered with the same error at the step where I try to reconstruct the datacube.

![Screenshot from 2022-10-28 11-57-00](https://user-images.githubusercontent.com/95560895/198518580-1de7803a-6119-404a-ae9d-bf0ce2c66043.png)

I have tried to run the example fits file but it still shows the same error. Although while trying multiple times, at one point it does actually worked but when i tried again the error comes back.

I would be grateful if you could help me out.

Thanks 
Arshi Ali

**Comment by remingtonsexton** [comment]
Hi, Arshi.  Could you please post or link your options and line list?  This will start to help me figure out what might have gone wrong.

**Comment by arshiali1701** [comment]
[BADASS3_ifu_MUSE.zip](https://github.com/remingtonsexton/BADASS3/files/9887614/BADASS3_ifu_MUSE.zip)

**Comment by remingtonsexton** [comment]
Thank, Arshi.  @smd1526 informed me that the latest version of the code does make sure to check for the key that is causing your error.  Is your version of the code the latest version?

**Comment by arshiali1701** [comment]
I think I'm using the latest version... although I have downloaded the repository around July so I'm not sure if there has been any update after that.

**Comment by arshiali1701** [comment]
Hi Remington,

Just letting you know that the problem is been solved . I guess the issue was indeed related to the updates. Thanks for the suggestions.

Thanks 
Arshi
